### ISSUE TITLE
Passing pretty false raises an exception

### ISSUE THREAD

**Issue by hatched-NicolasB** [michalmuskala/jason#54]
It looks like passing `pretty: false` to the encoder raises an exception.

```
pry(9)> Jason.encode(%{})
{:ok, "{}"}
pry(10)> Jason.encode(%{}, pretty: true)
{:ok, "{}"}
pry(11)> Jason.encode(%{}, pretty: false)
** (FunctionClauseError) no function clause matching in Jason.Formatter.parse_opts/5

    The following arguments were given to Jason.Formatter.parse_opts/5:

        # 1
        false

        # 2
        "  "

        # 3
        "\n"

        # 4
        nil

        # 5
        " "

    Attempted function clauses (showing 2 out of 2):

        defp parse_opts([{option, value} | opts], indent, line, record, colon)
        defp parse_opts([], indent, line, record, colon)

    (jason) lib/formatter.ex:122: Jason.Formatter.parse_opts/5
    (jason) lib/formatter.ex:66: Jason.Formatter.pretty_print_to_iodata/2
    (jason) lib/jason.ex:212: Jason.do_encode/2
    (jason) lib/jason.ex:125: Jason.encode/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (iex) lib/iex/evaluator.ex:249: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:229: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:207: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4
    (iex) lib/iex/pry.ex:64: IEx.Pry.pry/2
    (absinthe) lib/mix/tasks/absinthe.schema.json.ex:67: Mix.Tasks.Absinthe.Schema.Json.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by hlhr** [comment]
I checked this but I'm not sure how to fix it.

The only valid options are [`true` or a keyword of options](https://hexdocs.pm/jason/Jason.html#encode/2). False is no valid option. 
That means there are two ways to handle this:
1. Pattern match if pretty is false and call `Encode.encode(input, opts)`
2. Add guard (!=== false) to `defp do_encode(input, %{pretty: pretty} = opts)` [Code](https://github.com/michalmuskala/jason/blob/5941f266ee2daa6f5cc0efa967970af40de15cf5/lib/jason.ex#L210)
3. I missed something...

I llike the option 1 but I'm not sure about it. maybe @michalmuskala can give some feedback.

**Comment by sheharyarn** [comment]
I sent in a PR that fixes this (using the guard option @hlhr mentioned)

**Comment by michalmuskala** [comment]
Released in 1.1.2
